/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 2.0.25
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "CMPL_Time.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern const Meta_Repository __meta_repository_6B2BA18E126815D094B2D557823CBD68;

/*[1782]*/
static const Meta_Property
_CMPL_Time_SetTime_Time =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_IN,
    "Time",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    DATETIME,
    0,
    CIMPLE_OFF(CMPL_Time_SetTime_method,Time),
    0, /* value */
};

/*[1935]*/
static const Meta_Property
_CMPL_Time_SetTime_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(CMPL_Time_SetTime_method,return_value),
    0, /* value */
};

/*[1911]*/
static Meta_Feature* _CMPL_Time_SetTime_MFA[] =
{
    (Meta_Feature*)(void*)&_CMPL_Time_SetTime_Time,
    (Meta_Feature*)(void*)&_CMPL_Time_SetTime_return_value
};

/*[2113]*/
const Meta_Method
CMPL_Time_SetTime_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD|CIMPLE_FLAG_STATIC,
    "SetTime",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _CMPL_Time_SetTime_MFA,
    CIMPLE_ARRAY_SIZE(_CMPL_Time_SetTime_MFA),
    sizeof(CMPL_Time_SetTime_method),
    UINT32,
};

/*[1782]*/
static const Meta_Property
_CMPL_Time_GetTime_Time =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "Time",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    DATETIME,
    0,
    CIMPLE_OFF(CMPL_Time_GetTime_method,Time),
    0, /* value */
};

/*[1935]*/
static const Meta_Property
_CMPL_Time_GetTime_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(CMPL_Time_GetTime_method,return_value),
    0, /* value */
};

/*[1911]*/
static Meta_Feature* _CMPL_Time_GetTime_MFA[] =
{
    (Meta_Feature*)(void*)&_CMPL_Time_GetTime_Time,
    (Meta_Feature*)(void*)&_CMPL_Time_GetTime_return_value
};

/*[2113]*/
const Meta_Method
CMPL_Time_GetTime_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD|CIMPLE_FLAG_STATIC,
    "GetTime",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _CMPL_Time_GetTime_MFA,
    CIMPLE_ARRAY_SIZE(_CMPL_Time_GetTime_MFA),
    sizeof(CMPL_Time_GetTime_method),
    UINT32,
};

/*[2291]*/
static Meta_Feature* _CMPL_Time_MFA[] =
{
    (Meta_Feature*)(void*)&CMPL_Time_SetTime_method::static_meta_class,
    (Meta_Feature*)(void*)&CMPL_Time_GetTime_method::static_meta_class,
};

/*[2338]*/
static const Meta_Feature_Local _locals[] =
{
    {1},
    {1},
};

/*[2358]*/
const Meta_Class CMPL_Time::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_CLASS,
    "CMPL_Time",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _CMPL_Time_MFA,
    CIMPLE_ARRAY_SIZE(_CMPL_Time_MFA),
    sizeof(CMPL_Time),
    _locals,
    0, /* super_class */ 
    0, /* num_keys */
    &__meta_repository_6B2BA18E126815D094B2D557823CBD68,
};

CIMPLE_NAMESPACE_END

