//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 2.0.25
//
//==============================================================================

#include <cimple/cimple.h>
#include "repository.h"

CIMPLE_NAMESPACE_BEGIN

/*[2817]*/
static const Meta_Class* _meta_classes[] =
{
    &CMPL_Time::static_meta_class,
};

static const size_t _num_meta_classes = CIMPLE_ARRAY_SIZE(_meta_classes);

extern const Meta_Repository __meta_repository_6B2BA18E126815D094B2D557823CBD68;

/*[2844]*/
const Meta_Repository __meta_repository_6B2BA18E126815D094B2D557823CBD68 =
{
    _meta_classes,
    _num_meta_classes,
};

CIMPLE_NAMESPACE_END
