/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 2.0.25
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "CIM_InstCreation.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern const Meta_Repository __meta_repository_CB79DF59E9681ED7B2F09212824D7951;

/*[1566]*/
extern const Meta_Property
_CIM_Indication_IndicationIdentifier;

/*[1566]*/
extern const Meta_Property
_CIM_Indication_CorrelatedIndications;

/*[1566]*/
extern const Meta_Property
_CIM_Indication_IndicationTime;

/*[1566]*/
extern const Meta_Property
_CIM_Indication_PerceivedSeverity;

/*[1566]*/
extern const Meta_Property
_CIM_Indication_OtherSeverity;

extern const Meta_Reference
_CIM_InstIndication_SourceInstance;

/*[1566]*/
extern const Meta_Property
_CIM_InstIndication_SourceInstanceModelPath;

/*[1566]*/
extern const Meta_Property
_CIM_InstIndication_SourceInstanceHost;

/*[2289]*/
static Meta_Feature* _CIM_InstCreation_MFA[] =
{
    (Meta_Feature*)(void*)&_CIM_Indication_IndicationIdentifier,
    (Meta_Feature*)(void*)&_CIM_Indication_CorrelatedIndications,
    (Meta_Feature*)(void*)&_CIM_Indication_IndicationTime,
    (Meta_Feature*)(void*)&_CIM_Indication_PerceivedSeverity,
    (Meta_Feature*)(void*)&_CIM_Indication_OtherSeverity,
    (Meta_Feature*)(void*)&_CIM_InstIndication_SourceInstance,
    (Meta_Feature*)(void*)&_CIM_InstIndication_SourceInstanceModelPath,
    (Meta_Feature*)(void*)&_CIM_InstIndication_SourceInstanceHost,
};

/*[2336]*/
static const Meta_Feature_Local _locals[] =
{
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
};

/*[2356]*/
const Meta_Class CIM_InstCreation::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_INDICATION,
    "CIM_InstCreation",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _CIM_InstCreation_MFA,
    CIMPLE_ARRAY_SIZE(_CIM_InstCreation_MFA),
    sizeof(CIM_InstCreation),
    _locals,
    &CIM_InstIndication::static_meta_class,
    0, /* num_keys */
    &__meta_repository_CB79DF59E9681ED7B2F09212824D7951,
};

CIMPLE_NAMESPACE_END

