// Generated by genprov 2.0.25
#include "LC_InstCreation_Provider.h"

CIMPLE_NAMESPACE_BEGIN

LC_InstCreation_Provider::LC_InstCreation_Provider() : _indication_handler(0)
{
}

LC_InstCreation_Provider::~LC_InstCreation_Provider()
{
}

Load_Status LC_InstCreation_Provider::load()
{
    return LOAD_OK;
}

Unload_Status LC_InstCreation_Provider::unload()
{
    return UNLOAD_OK;
}

Enable_Indications_Status LC_InstCreation_Provider::enable_indications(
    Indication_Handler<LC_InstCreation>* indication_handler)
{
    _indication_handler = indication_handler;

    return ENABLE_INDICATIONS_OK;
}

Disable_Indications_Status LC_InstCreation_Provider::disable_indications()
{
    if (_indication_handler)
    {
        delete _indication_handler;
        _indication_handler = 0;
    }

    return DISABLE_INDICATIONS_OK;
}

/*@END@*/

CIMPLE_NAMESPACE_END
