/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 2.0.25
//
//==============================================================================

#ifndef _cimple_LC_InstCreation_h
#define _cimple_LC_InstCreation_h

#include <cimple/cimple.h>
#include "CIM_InstCreation.h"

CIMPLE_NAMESPACE_BEGIN

// LC_InstCreation keys:

/*[1192]*/
class LC_InstCreation : public Instance
{
public:
    // CIM_Indication features:
    Property<String> IndicationIdentifier;
    Property<Array_String> CorrelatedIndications;
    Property<Datetime> IndicationTime;
    Property<uint16> PerceivedSeverity;
    Property<String> OtherSeverity;

    // CIM_InstIndication features:
    Instance* SourceInstance;
    Property<String> SourceInstanceModelPath;
    Property<String> SourceInstanceHost;

    // CIM_InstCreation features:

    // LC_InstCreation features:

    CIMPLE_CLASS(LC_InstCreation)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_LC_InstCreation_h */
