// Generated by genprov 2.0.25
#ifndef _LC_InstCreation_Provider_h
#define _LC_InstCreation_Provider_h

#include <cimple/cimple.h>
#include "LC_InstCreation.h"
#includ "LC_Test.h"

CIMPLE_NAMESPACE_BEGIN

class LC_InstCreation_Provider
{
public:

    typedef LC_InstCreation Class;

    LC_InstCreation_Provider();

    ~LC_InstCreation_Provider();

    Load_Status load();

    Unload_Status unload();

    Enable_Indications_Status enable_indications(
        Indication_Handler<LC_InstCreation>* indication_handler);

    Disable_Indications_Status disable_indications();

    // User-added method to create and send an indication
    SendIndication(LC_Test *LC_new_instance);

    /*@END@*/
private:

    Indication_Handler<LC_InstCreation>* _indication_handler;
};

CIMPLE_NAMESPACE_END

#endif /* _LC_InstCreation_Provider_h */
