/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 2.0.25
//
//==============================================================================

#ifndef _cimple_LC_Test_h
#define _cimple_LC_Test_h

#include <cimple/cimple.h>

CIMPLE_NAMESPACE_BEGIN

// LC_Test keys:
//     Id

/*[1192]*/
class LC_Test : public Instance
{
public:
    // LC_Test features:
    Property<uint32> Id;
    Property<String> TestData;

    CIMPLE_CLASS(LC_Test)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_LC_Test_h */
