// Generated by genprov 2.0.25
#ifndef _LC_Test_Provider_h
#define _LC_Test_Provider_h

#include <cimple/cimple.h>
#include "LC_Test.h"

CIMPLE_NAMESPACE_BEGIN

class LC_Test_Provider
{
public:

    typedef LC_Test Class;

    LC_Test_Provider();

    ~LC_Test_Provider();

    Load_Status load();

    Unload_Status unload();

    Get_Instance_Status get_instance(
        const LC_Test* model,
        LC_Test*& instance);

    Enum_Instances_Status enum_instances(
        const LC_Test* model,
        Enum_Instances_Handler<LC_Test>* handler);

    Create_Instance_Status create_instance(
        LC_Test* instance);

    Delete_Instance_Status delete_instance(
        const LC_Test* instance);

    Modify_Instance_Status modify_instance(
        const LC_Test* model,
        const LC_Test* instance);

    /*@END@*/
};

CIMPLE_NAMESPACE_END

#endif /* _LC_Test_Provider_h */
