/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 2.0.25
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "LC_Test.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern const Meta_Repository __meta_repository_CB79DF59E9681ED7B2F09212824D7951;

/*[1566]*/
extern const Meta_Property
_LC_Test_Id;

/*[1589]*/
const Meta_Property
_LC_Test_Id =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_KEY|CIMPLE_FLAG_READ,
    "Id",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0, /* subscript */
    CIMPLE_OFF(LC_Test,Id),
    0, /* value */
};

/*[1566]*/
extern const Meta_Property
_LC_Test_TestData;

/*[1589]*/
const Meta_Property
_LC_Test_TestData =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "TestData",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    STRING,
    0, /* subscript */
    CIMPLE_OFF(LC_Test,TestData),
    0, /* value */
};

/*[2289]*/
static Meta_Feature* _LC_Test_MFA[] =
{
    (Meta_Feature*)(void*)&_LC_Test_Id,
    (Meta_Feature*)(void*)&_LC_Test_TestData,
};

/*[2336]*/
static const Meta_Feature_Local _locals[] =
{
    {1},
    {1},
};

/*[2356]*/
const Meta_Class LC_Test::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_CLASS,
    "LC_Test",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _LC_Test_MFA,
    CIMPLE_ARRAY_SIZE(_LC_Test_MFA),
    sizeof(LC_Test),
    _locals,
    0, /* super_class */ 
    1, /* num_keys */
    &__meta_repository_CB79DF59E9681ED7B2F09212824D7951,
};

CIMPLE_NAMESPACE_END

