//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 2.0.25
//
//==============================================================================

#include <cimple/cimple.h>
#include "repository.h"

CIMPLE_NAMESPACE_BEGIN

/*[2815]*/
static const Meta_Class* _meta_classes[] =
{
    &CIM_Indication::static_meta_class,
    &CIM_InstIndication::static_meta_class,
    &CIM_InstCreation::static_meta_class,
    &LC_InstCreation::static_meta_class,
};

static const size_t _num_meta_classes = CIMPLE_ARRAY_SIZE(_meta_classes);

extern const Meta_Repository __meta_repository_6FF88CC366261FACB440F949B95C94A9;

/*[2842]*/
const Meta_Repository __meta_repository_6FF88CC366261FACB440F949B95C94A9 =
{
    _meta_classes,
    _num_meta_classes,
};

CIMPLE_NAMESPACE_END
