//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 2.0.25
//
//==============================================================================

#ifndef _repository_h
#define _repository_h

#include <cimple/cimple.h>
#include "CIM_Indication.h"
#include "CIM_InstIndication.h"
#include "CIM_InstCreation.h"
#include "LC_InstCreation.h"

CIMPLE_NAMESPACE_BEGIN

CIMPLE_NAMESPACE_END

#endif /* _repository_h */
