//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 2.0.25
//
//==============================================================================

#include <cimple/cimple.h>
#include "repository.h"

CIMPLE_NAMESPACE_BEGIN

/*[2815]*/
static const Meta_Class* _meta_classes[] =
{
    &President::static_meta_class,
};

static const size_t _num_meta_classes = CIMPLE_ARRAY_SIZE(_meta_classes);

extern const Meta_Repository __meta_repository_BEF27DFE47411530AE0E2A4B4A11D1FB;

/*[2842]*/
const Meta_Repository __meta_repository_BEF27DFE47411530AE0E2A4B4A11D1FB =
{
    _meta_classes,
    _num_meta_classes,
};

CIMPLE_NAMESPACE_END
